### PR TITLE
Added basic top down, bottom up, left corner and bup code

### PR DESCRIPTION
**Pull request by AlexandruSimandi**
i did not check if the format is valid

### CODE REVIEW

**Comment by Vlaaaaaaad** [comment]
Thanks a lot!

I'll check this and merge it when I get home( later tonight or tomorrow morning).

**Comment by Vlaaaaaaad** [comment]
Doesn't look like the original code( the teachers code) so I will review this in more detail tomorrow. Nonetheless, thank you for your contribution!

**Comment by AlexandruSimandi** [comment]
it's the code from the lab exercises that i was too lazy to attend, it's working

**Comment by Vlaaaaaaad** [comment]
I'll merge this. The code is similar to the one in the book and I don't really have time to look it over.

Thanks a lot for contributing!

**Pull request merged**
